# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-29 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulos',
            name='horaspracticas16',
            field=models.CharField(blank=True, db_column='horaspracticas16', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modulos',
            name='horasteoricas16',
            field=models.CharField(blank=True, db_column='horasteoricas16', max_length=100, null=True),
        ),
    ]
