# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-01 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170929_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='nac',
            field=models.ForeignKey(blank=True, db_column='NAC_Id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.Catnacionalidad'),
        ),
        migrations.AlterField(
            model_name='evaluaciones',
            name='horaspractica27',
            field=models.FloatField(blank=True, db_column='HoerrasPractica27', null=True),
        ),
    ]
