# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-02 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20171001_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateducadores',
            name='ed_gradoalcanzado',
            field=models.CharField(blank=True, db_column='gradoalcanzado_Id', max_length=200, null=True, verbose_name=django.db.models.deletion.DO_NOTHING),
        ),
    ]
