# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-02 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20171002_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciones',
            name='horaspractica27',
            field=models.FloatField(blank=True, db_column='HorasPractica27', null=True),
        ),
    ]
