# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-29 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20171002_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciones',
            name='horaspractica30',
            field=models.FloatField(blank=True, db_column='HorasPractica30', null=True),
        ),
        migrations.AddField(
            model_name='evaluaciones',
            name='horasteoria30',
            field=models.FloatField(blank=True, db_column='HorasTeoria30', null=True),
        ),
        migrations.AddField(
            model_name='evaluaciones',
            name='notapractica29',
            field=models.FloatField(blank=True, db_column='NotaPractica29', null=True),
        ),
        migrations.AddField(
            model_name='evaluaciones',
            name='notapractica30',
            field=models.FloatField(blank=True, db_column='NotaPractica30', null=True),
        ),
        migrations.AddField(
            model_name='evaluaciones',
            name='notateorica30',
            field=models.FloatField(blank=True, db_column='NotaTeorica30', null=True),
        ),
    ]
