# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-31 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20171029_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluaciones',
            name='horaspractica30',
        ),
        migrations.RemoveField(
            model_name='evaluaciones',
            name='horasteoria30',
        ),
        migrations.RemoveField(
            model_name='evaluaciones',
            name='notapractica30',
        ),
        migrations.RemoveField(
            model_name='evaluaciones',
            name='notateorica30',
        ),
    ]
