# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-31 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20171031_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluaciones',
            name='notapractica29',
        ),
    ]
